# Generated by Django 4.1.4 on 2022-12-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
