# Generated by Django 4.1.4 on 2022-12-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hall', verbose_name='Зал'),
        ),
    ]
